### PR TITLE
Spelling and syntax fixes

### PR DESCRIPTION
**Pull request by MidnightLightning**
Fix some minor spelling and spacing issues

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Hey @MidnightLightning!
Looks like you have conflicts to resolve.    Maybe you started these changes just before @zelig's major reorg?   If so, I'm afraid you'll need to redo them.

Also, with regard to "dapp", we had a discussion on the gitter channel about DApps vs Dapps vs dapps vs ÐApp, and came to the conclusion that we should just use "dapp".   It's what it will end up being it the term moves into common use anyway, as e-mail -> email, and the use of ÐApp will, to quote myself, just make us look like pretentious tossers.

You had lots of other great changes, though, so PLEASE DO resolve the conflicts and/or just redo the edits except to move those all to "dapp" and it would be much appreciated.   Best wishes!

**Comment by MidnightLightning** [comment]
Oi, that was indeed a reorg! Updated now back to "dapp". And speaking of canonical forms, is "ether" a proper noun and should be "Ether" wherever it appears?

**Comment by bobsummerwill** [comment]
Fantastic!   Please could you squash these changes into a single commit?
"Ethereum" yes.
"Ether" ... hmm, yes, I suppose so ... @zelig @Souptacular @hughlang ?

**Comment by MidnightLightning** [comment]
Well, is "ether" just a currency name? Generally names of currencies aren't capitalized, right? e.g. "I gave Alice ten dollars for lunch." I've seen Bitcoin used as a proper noun, though, keeping both it's capital letter and not becoming plural. Ether nicely doesn't have to worry about plural or not!

**Comment by MidnightLightning** [comment]
And for squashing, since there's a merge/update from master, those commits can't be merged at this point. Do you want the ones that are past that merge squashed just for neatness?

**Comment by bobsummerwill** [comment]
Hmm.  I don't think that should make a difference should it?
You should be able to rebase on top of that merge-from-master and squash that down to a single commit, right?    Which is maybe what you are saying!    Yeah - just to avoid a bunch of commits in master after the PR merge.   Thanks!

**Pull request merged**
