### PR TITLE
FAQ cleanup first pass

### PR DESCRIPTION
**Pull request by hughlang**
Fix indented bullets hierarchy. Added links to software pages.

Still needs improvement of content. Let's discuss.

### CODE REVIEW

**Comment by Souptacular** [comment]
Whoops, I changed the FAQs before seeing this PR. I will merge your changes into it.

**Comment by Souptacular** [comment]
As far as other content improvement, I cleaned it up some by answering the unanswered questions and deleting questions that are based primarily on opinion ("What is the best/fastest/most stable client?"). Feel free open an issue to discuss what else in the FAQs need to be changed or submit another PR. Thanks for your help Hugh, you're a beast :+1:

**Comment by hughlang** [comment]
I think some of the links I added got lost. I will check and re-add in a new PR

**Comment by Souptacular** [comment]
If they did, my bad!

**Pull request closed without merging**
