### PR TITLE
CC BY 4.0

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by jamesray1** [comment]
@bobsummerwill, @Souptacular, @hughlang, @gmkung, @zelig, @pipermerriam, @yann300, @jjmstark, @chriseth, @5chdn, @ethers

**Comment by bobsummerwill** [comment]
So we never agreed to a license?  Well that was stupid.

IMHO we should use a Creative Commons license, if anything.

**Comment by jamesray1** [comment]
@bobsummerwill AIUI, an unlicense is pretty much the same as a CC4.0 license.

**Comment by jamesray1** [comment]
This is the unlicense template:

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org>

**Comment by jamesray1** [comment]
OK, it's not the same as CC4.0.
https://creativecommons.org/licenses/by/4.0/

**Comment by jamesray1** [comment]
Github doesn't have a license template for Creative Commons 4.0, but I've made one:

> The license for this repository is Creative Commons 4.0.
> 
> A human-readable summary (and not a substitute) of the license is [here](https://creativecommons.org/licenses/by/4.0/).
> 
> The license is [here](https://creativecommons.org/licenses/by/4.0/legalcode).

**Comment by 5chdn** [comment]
I'm fine with CC BY 4.0

**Comment by bobsummerwill** [comment]
Me too.

**Comment by pipermerriam** [comment]
I'm fine with this change.

**Comment by bobsummerwill** [comment]
@zelig was a major contributor too (by volume of content, not changelist count).   And @hudson too.

If Hudson and Viktor give their thumbs up then I think we are probably OK to proceed.

I doubt anybody would have any objection to CC licensing.

**Comment by jjmstark** [comment]
fwiw also fine with the license :)

**Comment by jamesray1** [comment]
I should mention that we should use CC BY-SA 4.0, where the major difference to CC BY 4.0 is: "Each SA license permits that you license adapations under any later version of the same CC license."

**Comment by jamesray1** [comment]
Don't actually merge this PR, since there are changes that shouldn't be merged. Just add this in a license file:

The license for this repository is CC BY-SA 4.0.

A human-readable summary (and not a substitute) of the license is [here](https://creativecommons.org/licenses/by-sa/4.0/).

The license is [here](https://creativecommons.org/licenses/by-sa/4.0/legalcode).

**Comment by bobsummerwill** [comment]
Please can you squash the PR?  Thanks!

**Comment by bobsummerwill** [comment]
And @gavofyork just used CC BY-SA 4.0 for the Yellow Paper too (thanks, Gav).

**Comment by jamesray1** [comment]
It might be good to get @zelig's approval before merging.

**Comment by jamesray1** [comment]
I just sent him a tweet as well.

**Comment by jamesray1** [comment]
Also @hughlang and @gmkung have more commits than Victor Tron, but may not have committed more sloc.

**Comment by pirapira** [comment]
@jamesray1 please squash the commits (read about `git rebase -i`).

  Currently, the commit history looks like, `UNLICENSE` was added and later changed into CC4.  So, somebody might fork off a branch from the `UNLICENSE` commit and start something.  That's not intended, right?

**Comment by jamesray1** [comment]
Sorry I can't figure out how to do that, I completed the rebase in Bash but can't figure out how to merge it.

**Pull request closed without merging**
