### PR TITLE
Looks like we have a Homestead-friendly release of ruby-ethereum :-)

### PR DESCRIPTION
**Pull request by bobsummerwill**
See https://twitter.com/janhxie/status/722256126922792960

### CODE REVIEW

**Comment by Souptacular** [comment]
Whoo!

**Comment by janx** [comment]
Link to v0.9.0: https://github.com/janx/ruby-ethereum/releases/tag/v0.9.0

**Comment by bobsummerwill** [comment]
Yeah - I've just left the link in that table pointing to the Gem for now.

If you would like to improve the https://github.com/ethereum/homestead-guide/tree/master/source/ethereum-clients/ruby-ethereum page, @janx, please do submit PRs, and we'll get them merged.    It's your ethdocs.org homepage :-)

**Comment by janx** [comment]
Looks nice :beers:

**Pull request merged**
