### PR TITLE
mining pool added

### PR DESCRIPTION
**Pull request by sneg55**

### CODE REVIEW

**Comment by sneg55** [comment]
@bobsummerwill  Hi Bob, do you mind to check my pull request? I'll  be much appreciated!

**Comment by bobsummerwill** [comment]
I am sorry, but I do not have commit rights.

**Comment by sneg55** [comment]
Okay, I'll try to ask @chriseth

**Comment by sneg55** [comment]
@pirapira  Thanks, when this PR goes live on ethdocs.org / ethereum-homestead.readthedocs.io ?

**Comment by pirapira** [comment]
I don't know.  I thought it's automatic.

**Pull request merged**
