### PR TITLE
Modify reference to ethereum/wiki, remove ethereum/wiki from legacy docs as it is actively maintained (moreso than this repo) and place it prominently as an alternative to this repo/site

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by jamesray1** [comment]
Before you merge this, I will reference the wiki.

**Comment by paulvi** [comment]
Great.

There are others things to do to clear up status of the docs. Let it be in #441

**Comment by paulvi** [comment]
OK, waiting for merge

than https://github.com/ethereum/homestead-guide/blob/master/source/index.rst would need to be changed as it is front page http://ethdocs.org/en/latest/

**Comment by paulvi** [comment]
> Suddenly the PR retires the homestead guide. I'll make a shout on gitter.im/ethereum/homestead-guide.

Possibly something was configured outside of this repo...

**Comment by pirapira** [comment]
@paulvi this sentence retires the Homestead guide

> The Guide may be considered to be a historic reference since Ethereum had the Metropolis phase 1 fork,

**Comment by paulvi** [comment]
yes, but not immediately.

First step is within README to guide where docs updates should go.

**Comment by paulvi** [comment]
please merge

**Comment by pirapira** [comment]
I don't want back-and-forth.  If we retire it, we do it completely, like changing the colors of text so it looks obsolete, etc.  I first need some silence on that channel first because if anybody wants to update this repo, this document cannot be considered as a historic one.

**Comment by paulvi** [comment]
What should be there is one place to be called "Ethereum docs".

Currently it is wiki/wiki vs http://ethdocs.org (this repo)

And with this PR it would be retiring.  

> I've asked if anybody is interested to upgrade the Homestead guide. https://gitter.im/ethereum/homestead-guide I'll give them 48 hours to respond.

That is pretty good. After few days (weekend),  go on with updates.
Also #443 http://ethdocs.org target can be changed.

**Comment by pirapira** [comment]
> should be there is one place to be called "Ethereum docs".

No I don't think so.

I just want to clarify if this repo is retired or not.

**Pull request merged**
