### PR TITLE
Refreshed our list of contributors.

### PR DESCRIPTION
**Pull request by bobsummerwill**
We have accepted various PRs since Homestead without crediting people.

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Hey @12v, @azulmarino, @c0d3inj3cT, @giact, @kclowes, @LucaTony, @madhancr, @Omkara, @tflux99, @xyzether!    So you are all currently in the pseudonymous section.    If any of your would like to "uncloak", please could you let me the real name you would like listed?     I know that I have asked that of some of you already, but not all of you.

So perhaps, to avoid badgering you further, if you WOULD or WOULD NOT like to be unmasked, please could you reply with your preference?    If you explicitly WOULD NOT like to be unmasked, I can make a new section in the document, so we can record that you are intentionally pseudonymous, rather than accidentally, and stop asking :-)    Thanks!

**Comment by azulmarino** [comment]
Azulmarino = Dean Alain Vernon 

Best regards,

Dean

**Comment by kclowes** [comment]
@kclowes: Keri Clowes

Thanks!

**Comment by giact** [comment]
Yes please, use my real name: giact = Giacomo Tazzari

**Comment by bobsummerwill** [comment]
Thanks, Dean and Keri.   Updated!

And thanks again for your contributions everybody.   Much appreciated :-)

We've had a bit of a lull on documentation after Homestead, but should be a little more active again in the coming weeks and months.    All PRs gratefully received!

**Comment by bobsummerwill** [comment]
Thanks, Giacomo.   Done!

**Comment by Souptacular** [comment]
Looks good to me. Merge when ready.

**Comment by bobsummerwill** [comment]
DONE!

**Pull request merged**
