### PR TITLE
Add Karsha Exchange

### PR DESCRIPTION
**Pull request by khashmeshab**

### CODE REVIEW

**Comment by khashmeshab** [comment]
Hello,

It's been around two months, but no one even responded to this PR yet.

P.S. We are also listed at:
https://bitcoin.org/en/exchanges
https://www.bitcoincash.org/#exchanges
https://getmonero.org/community/merchants/

**Comment by pirapira** [comment]
I'm not comfortable maintaining lists of businesses.  See https://github.com/ethereum/homestead-guide/pull/414

**Comment by jamesray1** [comment]
@khashmeshab You could edit this: https://github.com/ethereum/wiki/wiki/Decentralized-apps-(dapps)

**Comment by khashmeshab** [comment]
@jamesray1 Are you sure our business (non-decentralized exchange) is related to that article? If you, may you point out where should I add it? Thanks.

**Comment by khashmeshab** [comment]
@jamesray1 Thank you. Added it to the "Centralised fixed rate exchanges" section.

**Pull request closed without merging**
