### PR TITLE
Add a license: CC-BY-SA 4.0

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by jamesray1** [comment]
Replaces #413.

**Comment by pirapira** [comment]
@zelig's approval is still pending.

**Comment by jamesray1** [comment]
Should we get approval from @hughlang and @gmkung as well? Is there any other way to get in touch with these guys and @zelig? Can you guys confirm whether you have read these comments? We just need you to approve the use of a [CC-BY-SA 4.0 license](https://creativecommons.org/licenses/by-sa/4.0/).

**Comment by jamesray1** [comment]
I sent emails to @zelig, @hughlang and @gmkung requesting that they approve the license.

**Comment by gmkung** [comment]
Hi all, sorry for the delay in reply. Yes I approve of this change.

**Comment by jamesray1** [comment]
Thanks @gmkung, for your contributions and for the approval! That's OK, the delay is understandable.

**Comment by jamesray1** [comment]
Thanks @zelig!

**Pull request merged**
