### PR TITLE
Steps for dependencies on Ubuntu Xenial 16.04

### PR DESCRIPTION
**Pull request by giact**
These are the steps I used to install dependencies (and then compile from source and run mix-ide) on a clean Ubuntu Xenial 16.04 virtual machine.
I have not tested runtime behavior yet.

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Great - thanks for that, @giact.

I think that @phonikg might have done some Xenial runs.   Have you, John?

**Comment by phonikg** [comment]
Yes @bobsummerwill I have installed both from PPA and also built `geth` from source... no issues.  Worked "out of the box" with standard instructions.

**Comment by phonikg** [comment]
Let me know how I can perform runtime tests and I can assist.

**Comment by bobsummerwill** [comment]
I don't think we need anything heavy weight, @phonikg.

Just confirmation that you can `app-get install` on Xenial, and run them and they seem to be syncing OK.

And then we'll remove the caveat here.   Anything else which comes up will be "just bugs" like for any other platform.

**Comment by phonikg** [comment]
Consider it confirmed for `geth`, will test `eth` when I get home tonight.

/Me sets reminder in phone...

**Comment by giact** [comment]
By the way: in the very last step I added installation for packages `qml-module-qtquick-privatewidgets`, `qml-module-qtquick-dialogs`, `qml-module-qt-labs-settings` and `qml-module-qtgraphicaleffects` because they are later required by `mix-ide` at runtime.

I suppose that's necessary for the previous versions of Ubuntu as well, but I haven't actually tested it yet.

**Comment by bobsummerwill** [comment]
Thanks, @giact.

When we have got Mix, Solidity and cpp-ethereum split apart nicely, we will be able to strip these down much more.

See my work-in-progress at https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/setup.sh, for example.

And Solidity is even better :-)

Look at these minimal beauties on OS X, for example - https://github.com/bobsummerwill/solidity/blob/solidity_standalone/setup.sh#L27.

**Comment by bobsummerwill** [comment]
OK - Let's merge as-is, and we can trim it a bit more soon :-)

Thanks, guys!

**Comment by bobsummerwill** [comment]
Oh - I already did merge, didn't I.    Ha ha!

**Comment by phonikg** [comment]
😂

**Pull request merged**
