### PR TITLE
Update contributors list for Homestead Guide.

### PR DESCRIPTION
**Pull request by bobsummerwill**
My first pull request.   I started with a very simple one - just updating the contributors guide to include everybody who has had a commit "landed" in the repo.    I already used with simple use-case to start to learn the RST markup syntax.

I also added a .gitignore file to mask out the `build` directory, which is comprised of built files which you would never want to commit, or even to have show up in `git status`.

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Hey @c0d3inj3cT, @gmkung, @jmahhh, @klmoney and @LiteBit.

I have added you all to the contributor credit pseudonymously.   If any of you would like to "unmask" then please reply here and we can update the document accordingly.   Thanks!

**Comment by jmahhh** [comment]
Hey! I go by Joël Hubert ;)

**Comment by bobsummerwill** [comment]
Aha - thanks!   -> https://github.com/ethereum/homestead-guide/pull/49

**Comment by gmkung** [comment]
And me by Guangmian Kung ;)

**Comment by bobsummerwill** [comment]
Thanks!  Added to #49 as well!

**Comment by c0d3inj3cT** [comment]
Hey Bob,

And me by Sudeep Singh.

Thanks!

**Comment by bobsummerwill** [comment]
@c0d3inj3cT Added to #49.   Thanks!

**Pull request merged**
