### PR TITLE
Demoting myself to Contributors section

### PR DESCRIPTION
**Pull request by hughlang**

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Hey, @klmoney, @LiteBit, @azulmarino and @madhancr!

Last chance for any of who want to "unmask" before Homestead, so that your contributions to the documentation are associated with your true names.

Understand completely if you are intentionally pseudonymous.    Just want to give you the opportunity if you want it.

See http://docs.ethereum.org/en/latest/introduction/contributors.html.   Thanks!

**Comment by klmoney** [comment]
Hi @bobsummerwill, I would like to use my name, Chandra Kumar. Should I do a PR?

**Comment by klmoney** [comment]
OK, done.

**Comment by LiteBit** [comment]
You can use my real life name, Paul Schmitzer.

**Comment by bobsummerwill** [comment]
Done, @LiteBit.   https://github.com/ethereum/homestead-guide/pull/151.   Thanks!

**Pull request merged**
