### PR TITLE
Updated trustless services

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by pirapira** [comment]
I'm not comfortable maitaining business directories.  See #414

**Comment by jamesray1** [comment]
Haha, fair enough, I guess. But I guess if the information goes out-of-date you could just leave it and say that it might go out of date and that it won't be maintained?

**Comment by pirapira** [comment]
I'm open to the possibility that other people maintain it.

**Comment by jamesray1** [comment]
I don't want to commit to actively maintaining it, but if I had write access I could accept PRs from people who want to maintain it. At any rate I've already created one [here](https://github.com/ethereum/wiki/wiki/Decentralized-apps-(dapps).md).

**Comment by pirapira** [comment]
Ah, maybe the list can move to the wiki, and there anyone can edit the list.

**Comment by jamesray1** [comment]
Yes I made some commits to do that.

**Pull request merged**
